### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ServicesConfig' not found 

### ISSUE THREAD

**Issue by codetestmg** [globalpayments/php-sdk#61] opened 2020-11-16 11:04 UTC
Fatal error: Uncaught Error: Class 'ServicesConfig' not found in index.php:17 Stack trace: #0 {main} thrown in index.php on line 17

use GlobalPayments\Api\ServicesConfig;
$config = new ServicesConfig();

**Comment by codetestmg** [comment] 2020-11-16 11:05
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once('vendor/autoload.php');

use GlobalPayments\Api\Entities\Address;
use GlobalPayments\Api\Entities\Enums\AddressType;
use GlobalPayments\Api\ServiceConfigs;
use GlobalPayments\Api\HostedPaymentConfig;
use GlobalPayments\Api\Entities\HostedPaymentData;
use GlobalPayments\Api\Entities\Enums\HppVersion;
use GlobalPayments\Api\Entities\Exceptions\ApiException;
use GlobalPayments\Api\Services\HostedService;

// configure client, request and HPP settings
$config = new ServicesConfig();

**Comment by MSmedal** [comment] 2020-11-16 14:28
Hello!

In v2.1.0 we changed the SDK's gateway configuration handling. The config handling [here](https://github.com/globalpayments/php-sdk/blob/master/test/Integration/Gateways/PorticoConnector/Certifications/EcommerceTest.php#L329-L346) is a good example to work from if needed. In a nutshell, the change is that each gateway now has a named serviceConfig instead of all of the gateways working from the same class/obj.

**Comment by izamzam2020** [comment] 2020-11-19 12:03
I'm having this issue even after updating to 2.1.0 - I get the following error

Declaration of GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig::configureContainer($services) must be compatible with GlobalPayments\Api\ServiceConfigs\Configuration::configureContainer(GlobalPayments\Api\ConfiguredServices $services)

**Comment by liamdv4** [comment] 2020-11-27 15:55
Same here. Did you manage to figure it out? I'm using 2.1.2

**Comment by anburaja-2020** [comment] 2020-11-28 06:08
I am having the same issue. could you please provide the solution

**Comment by izamzam2020** [comment] 2020-11-28 08:31
Called them mutiple times and have emailed their support,  they know about the issue but haven't bothered to respond   with a fix or have some one call me back as promised. 

I'll update the ticket when/If I hear back

**Comment by liamdv4** [comment] 2020-11-30 09:10
I've tried upgrading to 2.2.1 but that hasn't helped. I can get past it by making a couple of changes in GpEcomConfig.php:

1. Add use GlobalPayments\Api\ConfiguredServices;
2. Change line 38 to: public function configureContainer(ConfiguredServices$services) 

However, I'm now hitting problems later in the process. I'm reluctant to submit this as a pull request because without documentation on the SDK architecture I've no idea whether this is a hack or a real fix. 

In any event, we're not in a great situation with the SCA deadline so close.

**Comment by izamzam2020** [comment] 2020-11-30 09:15
> I've tried upgrading to 2.2.1 but that hasn't helped. I can get past it by making a couple of changes in GpEcomConfig.php:
> 
> 1. Add use GlobalPayments\Api\ConfiguredServices;
> 2. Change line 38 to: public function configureContainer(ConfiguredServices$services)
> 
> However, I'm now hitting problems later in the process. I'm reluctant to submit this as a pull request because without documentation on the SDK architecture I've no idea whether this is a hack or a real fix.
> 
> In any event, we're not in a great situation with the SCA deadline so close.

Thanks for that - I also managed to get passed the first error but then like you run into further issues. I don't really want to hack the script up as when they update our code will stop working.

It's shocking how bad their support is, if they bother to respond ill update you.

Cheers
Ian

**Comment by MSmedal** [comment] 2021-01-05 16:52
I'm having trouble duplicating your issue. I just used what I'll paste below to test 2.1.0, 2.1.2, and 2.2.2 (just released a bit ago) without issue:

`<?php

require_once('vendor/autoload.php');

use GlobalPayments\Api\PaymentMethods\CreditCardData;
use GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig; // add this of course
use GlobalPayments\Api\ServicesContainer;

$config = new GpEcomConfig(); // named gateway config
$config->merchantId = 'heartlandgpsandbox'; 
$config->accountId = 'api';
$config->sharedSecret = 'secret';
$config->rebatePassword = 'rebate';
$config->refundPassword = 'refund';
$config->serviceUrl = 'https://api.sandbox.realexpayments.com/epage-remote.cgi';

ServicesContainer::configureService($config); // configureService replaces configure

$card = new CreditCardData();
$card->number = '4111111111111111';
$card->expMonth = 12;
$card->expYear = 2021;
$card->cvn = '123';
$card->cardHolderName = 'Joe Smith';

$response = $card->charge(5.67)
    ->withCurrency('USD')
    ->execute();

print_r($response);
`

Can you have a look at the authentication configuration bits, especially the 2-3 lines I commented, and verify it matches what you're using? This example should work for ^2.1 using the RealEx/GlobalPayments gateway.

Apologies for the delayed response. Please feel free to email us at developers@globalpay.com for immediate assistance with this or any other development issues or questions.

**Comment by legitalk** [comment] 2021-01-08 11:32
Based on this - https://github.com/globalpayments/php-sdk/issues/76, the problem can be, because composer did not add ServicesConfig.php to autoload, as it was not PSR-4. This should be now fixed. Am I right, @MSmedal ?

**Comment by Spilaney** [comment] 2021-01-08 21:40
We're having exactly the same issue, updated to 2.2.3 and no difference I'm afraid. Replaced our code for MSmedal's sample above for confirmation and the same issue still.

Confirmed with a clean install of composer and the 2.2.3, same problem it seems.

**Comment by MSmedal** [comment] 2021-01-09 15:54
> Based on this - #76, the problem can be, because Composer (version 2.0.8) did not add ServicesConfig.php to autoload, as it was not PSR-4. This should be now fixed. Am I right, @MSmedal ?

I don't think the issue fixed with 2.2.3 is related to this one @legitalk , but I'm having trouble recreating what I think is being described on this issue so I'm not sure.

@Spilaney , could you provide the error stack trace you see when running my example?

**Comment by Spilaney** [comment] 2021-01-09 17:16
@MSmedal of course, its similar as supplied previously. 

PHP Fatal error:  Declaration of GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig::configureContainer($services) must be compatible with GlobalPayments\Api\ServiceConfigs\Configuration::configureContainer(GlobalPayments\Api\ConfiguredServices $services) in /var/www/dev/vendor/globalpayments/php-sdk/src/ServiceConfigs/Gateways/GpEcomConfig.php on line 13

Prior to your suggested code though, it was just

PHP Fatal error:  Uncaught Error: Class 'GlobalPayments\Api\ServicesConfig' not found in /var/www/dev/charge.php:16

After reading a few other issues regarding the Declaration, i checked the php version on my test rig and updated it to 7.3 and that did the trick. It would seem prior to this version it definitely didn't like it. So working now

**Closed** 2022-04-19 13:13 UTC
